C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,3)*ProjM(4,1)
C     
      SUBROUTINE FFFF1P1N_4(F1, F2, F3, COUP,F4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 F4(6)
      COMPLEX*16 TMP19
      TMP19 = (F2(3)*F3(3)+F2(4)*F3(4))
      F4(3)= COUP*(-CI )* TMP19*F1(3)
      F4(4)= COUP*(-CI )* TMP19*F1(4)
      F4(5)= COUP*0D0
      F4(6)= COUP*0D0
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,3)*ProjM(4,1)
C     
      SUBROUTINE FFFF1_15_16_17_5_9P1N_4(F1, F2, F3, COUP1, COUP2,
     $  COUP3, COUP4, COUP5, COUP6,F4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 F4(6)
      COMPLEX*16 FTMP(6)
      INTEGER*4 I
      CALL FFFF1P1N_4(F1,F2,F3,COUP1,F4)
      CALL FFFF15P1N_4(F1,F2,F3,COUP2,FTMP)
      DO I = 3, 6
        F4(I) = F4(I) + FTMP(I)
      ENDDO
      CALL FFFF16P1N_4(F1,F2,F3,COUP3,FTMP)
      DO I = 3, 6
        F4(I) = F4(I) + FTMP(I)
      ENDDO
      CALL FFFF17P1N_4(F1,F2,F3,COUP4,FTMP)
      DO I = 3, 6
        F4(I) = F4(I) + FTMP(I)
      ENDDO
      CALL FFFF5P1N_4(F1,F2,F3,COUP5,FTMP)
      DO I = 3, 6
        F4(I) = F4(I) + FTMP(I)
      ENDDO
      CALL FFFF9P1N_4(F1,F2,F3,COUP6,FTMP)
      DO I = 3, 6
        F4(I) = F4(I) + FTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,3)*ProjM(4,1)
C     
      SUBROUTINE FFFF1_15_16_17_9P1N_4(F1, F2, F3, COUP1, COUP2, COUP3
     $ , COUP4, COUP5,F4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 F4(6)
      COMPLEX*16 FTMP(6)
      INTEGER*4 I
      CALL FFFF1P1N_4(F1,F2,F3,COUP1,F4)
      CALL FFFF15P1N_4(F1,F2,F3,COUP2,FTMP)
      DO I = 3, 6
        F4(I) = F4(I) + FTMP(I)
      ENDDO
      CALL FFFF16P1N_4(F1,F2,F3,COUP3,FTMP)
      DO I = 3, 6
        F4(I) = F4(I) + FTMP(I)
      ENDDO
      CALL FFFF17P1N_4(F1,F2,F3,COUP4,FTMP)
      DO I = 3, 6
        F4(I) = F4(I) + FTMP(I)
      ENDDO
      CALL FFFF9P1N_4(F1,F2,F3,COUP5,FTMP)
      DO I = 3, 6
        F4(I) = F4(I) + FTMP(I)
      ENDDO
      END


