C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1)*ProjM(4,3)
C     
      SUBROUTINE FFFF2P1N_4(F1, F2, F3, COUP,F4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 F4(6)
      COMPLEX*16 TMP0
      TMP0 = (F2(3)*F1(3)+F2(4)*F1(4))
      F4(3)= COUP*(-CI )* F3(3)*TMP0
      F4(4)= COUP*(-CI )* F3(4)*TMP0
      F4(5)= COUP*0D0
      F4(6)= COUP*0D0
      END


