C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1)*ProjP(4,3)
C     
      SUBROUTINE FFFF10_0(F1, F2, F3, F4, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 F4(*)
      COMPLEX*16 TMP0
      COMPLEX*16 TMP8
      COMPLEX*16 VERTEX
      TMP0 = (F2(3)*F1(3)+F2(4)*F1(4))
      TMP8 = (F4(5)*F3(5)+F4(6)*F3(6))
      VERTEX = COUP*(-CI * TMP8*TMP0)
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1)*ProjP(4,3)
C     
      SUBROUTINE FFFF10_14_18_19_6_8_0(F1, F2, F3, F4, COUP1, COUP2,
     $  COUP3, COUP4, COUP5, COUP6,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 F4(*)
      COMPLEX*16 TMP
      COMPLEX*16 VERTEX
      CALL FFFF10_0(F1,F2,F3,F4,COUP1,VERTEX)
      CALL FFFF14_0(F1,F2,F3,F4,COUP2,TMP)
      VERTEX = VERTEX + TMP
      CALL FFFF18_0(F1,F2,F3,F4,COUP3,TMP)
      VERTEX = VERTEX + TMP
      CALL FFFF19_0(F1,F2,F3,F4,COUP4,TMP)
      VERTEX = VERTEX + TMP
      CALL FFFF6_0(F1,F2,F3,F4,COUP5,TMP)
      VERTEX = VERTEX + TMP
      CALL FFFF8_0(F1,F2,F3,F4,COUP6,TMP)
      VERTEX = VERTEX + TMP
      END


