C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(4,3)*ProjP(2,1)
C     
      SUBROUTINE FFFF8P1N_3(F1, F2, F4, COUP,F3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(6)
      COMPLEX*16 F4(*)
      COMPLEX*16 TMP1
      TMP1 = (F2(5)*F1(5)+F2(6)*F1(6))
      F3(3)= COUP*(-CI )* F4(3)*TMP1
      F3(4)= COUP*(-CI )* F4(4)*TMP1
      F3(5)= COUP*0D0
      F3(6)= COUP*0D0
      END


