C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjP(2,3)*ProjP(4,1)
C     
      SUBROUTINE FFFF9P1N_4(F1, F2, F3, COUP,F4)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(*)
      COMPLEX*16 F4(6)
      COMPLEX*16 TMP25
      TMP25 = (F2(5)*F3(5)+F2(6)*F3(6))
      F4(3)= COUP*0D0
      F4(4)= COUP*0D0
      F4(5)= COUP*(-CI )* TMP25*F1(5)
      F4(6)= COUP*(-CI )* TMP25*F1(6)
      END


