C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1) - ProjP(2,1)
C     
      SUBROUTINE FFS2P1N_3(F1, F2, COUP,S3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 S3(3)
      COMPLEX*16 TMP0
      COMPLEX*16 TMP1
      TMP0 = (F2(3)*F1(3)+F2(4)*F1(4))
      TMP1 = (F2(5)*F1(5)+F2(6)*F1(6))
      S3(3)= COUP*(-CI*(TMP0)+CI*(TMP1))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1) - ProjP(2,1)
C     
      SUBROUTINE FFS2_4P1N_3(F1, F2, COUP1, COUP2,S3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 S3(3)
      COMPLEX*16 STMP(3)
      INTEGER*4 I
      CALL FFS2P1N_3(F1,F2,COUP1,S3)
      CALL FFS4P1N_3(F1,F2,COUP2,STMP)
      DO I = 3, 3
        S3(I) = S3(I) + STMP(I)
      ENDDO
      END


