C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1) - ProjP(2,1)
C     
      SUBROUTINE FFS2_0(F1, F2, S3, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 S3(*)
      COMPLEX*16 TMP15
      COMPLEX*16 TMP16
      COMPLEX*16 VERTEX
      TMP15 = (F2(3)*F1(3)+F2(4)*F1(4))
      TMP16 = (F2(5)*F1(5)+F2(6)*F1(6))
      VERTEX = COUP*S3(3)*(-CI*(TMP15)+CI*(TMP16))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     ProjM(2,1) - ProjP(2,1)
C     
      SUBROUTINE FFS2_4_0(F1, F2, S3, COUP1, COUP2,VERTEX)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 S3(*)
      COMPLEX*16 TMP
      COMPLEX*16 VERTEX
      CALL FFS2_0(F1,F2,S3,COUP1,VERTEX)
      CALL FFS4_0(F1,F2,S3,COUP2,TMP)
      VERTEX = VERTEX + TMP
      END


