ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MTA,MDL_MB,MDL_MZ,MDL_MH,MDL_MW,MDL_MT

      COMMON/MASSES/ MDL_MTA,MDL_MB,MDL_MZ,MDL_MH,MDL_MW,MDL_MT


      DOUBLE PRECISION MDL_WT,MDL_WZ,MDL_WW,MDL_WH

      COMMON/WIDTHS/ MDL_WT,MDL_WZ,MDL_WW,MDL_WH


      DOUBLE COMPLEX GC_6, GC_7, GC_727, GC_1, GC_2, GC_649, GC_650,
     $  GC_660, GC_593, GC_725

      COMMON/COUPLINGS/ GC_6, GC_7, GC_727, GC_1, GC_2, GC_649, GC_650
     $ , GC_660, GC_593, GC_725

