ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP9()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_774 = (MDL_CTZIX31*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ +(MDL_CTZX31*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_775 = -((MDL_CTZIX32*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ )+(MDL_CTZX32*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_776 = (MDL_CTZIX32*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ +(MDL_CTZX32*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_797 = -((MDL_CTGIX13*MDL_GSTRONG*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))+(MDL_CTGX13*MDL_COMPLEXI*MDL_GSTRONG*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_798 = (MDL_CTGIX13*MDL_GSTRONG*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)+(MDL_CTGX13*MDL_COMPLEXI*MDL_GSTRONG*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_799 = -((MDL_CTGIX23*MDL_GSTRONG*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))+(MDL_CTGX23*MDL_COMPLEXI*MDL_GSTRONG*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_800 = (MDL_CTGIX23*MDL_GSTRONG*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)+(MDL_CTGX23*MDL_COMPLEXI*MDL_GSTRONG*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_801 = -((MDL_CTGIX31*MDL_GSTRONG*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))+(MDL_CTGX31*MDL_COMPLEXI*MDL_GSTRONG*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_802 = (MDL_CTGIX31*MDL_GSTRONG*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)+(MDL_CTGX31*MDL_COMPLEXI*MDL_GSTRONG*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_803 = -((MDL_CTGIX32*MDL_GSTRONG*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))+(MDL_CTGX32*MDL_COMPLEXI*MDL_GSTRONG*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_804 = (MDL_CTGIX32*MDL_GSTRONG*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)+(MDL_CTGX32*MDL_COMPLEXI*MDL_GSTRONG*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_911 = -((MDL_CTPIX13*MDL_VEV__EXP__2)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))+(MDL_CTPX13*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_912 = (MDL_CTPIX13*MDL_VEV__EXP__2)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)+(MDL_CTPX13*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_913 = -((MDL_CTPIX23*MDL_VEV__EXP__2)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))+(MDL_CTPX23*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_914 = (MDL_CTPIX23*MDL_VEV__EXP__2)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)+(MDL_CTPX23*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_915 = -((MDL_CTPIX31*MDL_VEV__EXP__2)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))+(MDL_CTPX31*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_916 = (MDL_CTPIX31*MDL_VEV__EXP__2)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)+(MDL_CTPX31*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_917 = -((MDL_CTPIX32*MDL_VEV__EXP__2)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))+(MDL_CTPX32*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_918 = (MDL_CTPIX32*MDL_VEV__EXP__2)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)+(MDL_CTPX32*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_953 = -((MDL_COMPLEXI*MDL_YB)/MDL_SQRT__2)
      GC_954 = -((MDL_COMPLEXI*MDL_YT)/MDL_SQRT__2)
      END
