ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MB,MDL_MW,MDL_MT,MDL_MH,MDL_MZ,MDL_MTA

      COMMON/MASSES/ MDL_MB,MDL_MW,MDL_MT,MDL_MH,MDL_MZ,MDL_MTA


      DOUBLE PRECISION MDL_WZ,MDL_WW,MDL_WH,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WW,MDL_WH,MDL_WT


      DOUBLE COMPLEX GC_7, GC_1, GC_2, GC_649, GC_650, GC_660, GC_593,
     $  GC_725

      COMMON/COUPLINGS/ GC_7, GC_1, GC_2, GC_649, GC_650, GC_660,
     $  GC_593, GC_725

