ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP2()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_861 = -((MDL_CBWIX31*MDL_SW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))-(MDL_CBWX31*MDL_COMPLEXI*MDL_SW*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_862 = (MDL_CBWIX31*MDL_SW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)-(MDL_CBWX31*MDL_COMPLEXI*MDL_SW*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_863 = -((MDL_CBWIX32*MDL_SW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))-(MDL_CBWX32*MDL_COMPLEXI*MDL_SW*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_864 = (MDL_CBWIX32*MDL_SW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)-(MDL_CBWX32*MDL_COMPLEXI*MDL_SW*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_865 = -((MDL_CTZIX13*MDL_CW*MDL_VEV)/MDL_LAMBDA__EXP__2)
     $ +(MDL_CTZX13*MDL_CW*MDL_COMPLEXI*MDL_VEV)/MDL_LAMBDA__EXP__2
     $ -(MDL_CTAIX13*MDL_SW*MDL_VEV)/MDL_LAMBDA__EXP__2+(MDL_CTAX13
     $ *MDL_COMPLEXI*MDL_SW*MDL_VEV)/MDL_LAMBDA__EXP__2
      GC_866 = (MDL_CTZIX13*MDL_CW*MDL_VEV)/MDL_LAMBDA__EXP__2
     $ +(MDL_CTZX13*MDL_CW*MDL_COMPLEXI*MDL_VEV)/MDL_LAMBDA__EXP__2
     $ +(MDL_CTAIX13*MDL_SW*MDL_VEV)/MDL_LAMBDA__EXP__2+(MDL_CTAX13
     $ *MDL_COMPLEXI*MDL_SW*MDL_VEV)/MDL_LAMBDA__EXP__2
      GC_867 = -((MDL_CTZIX23*MDL_CW*MDL_VEV)/MDL_LAMBDA__EXP__2)
     $ +(MDL_CTZX23*MDL_CW*MDL_COMPLEXI*MDL_VEV)/MDL_LAMBDA__EXP__2
     $ -(MDL_CTAIX23*MDL_SW*MDL_VEV)/MDL_LAMBDA__EXP__2+(MDL_CTAX23
     $ *MDL_COMPLEXI*MDL_SW*MDL_VEV)/MDL_LAMBDA__EXP__2
      GC_868 = (MDL_CTZIX23*MDL_CW*MDL_VEV)/MDL_LAMBDA__EXP__2
     $ +(MDL_CTZX23*MDL_CW*MDL_COMPLEXI*MDL_VEV)/MDL_LAMBDA__EXP__2
     $ +(MDL_CTAIX23*MDL_SW*MDL_VEV)/MDL_LAMBDA__EXP__2+(MDL_CTAX23
     $ *MDL_COMPLEXI*MDL_SW*MDL_VEV)/MDL_LAMBDA__EXP__2
      GC_919 = -((MDL_CPQ3IX31*MDL_EE*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SW*MDL_SQRT__2))+(MDL_CPQ3X31*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(MDL_LAMBDA__EXP__2*MDL_SW
     $ *MDL_SQRT__2)
      GC_920 = (MDL_CPQ3IX31*MDL_EE*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SW*MDL_SQRT__2)+(MDL_CPQ3X31*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(MDL_LAMBDA__EXP__2*MDL_SW
     $ *MDL_SQRT__2)
      GC_921 = -((MDL_CPQ3IX32*MDL_EE*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SW*MDL_SQRT__2))+(MDL_CPQ3X32*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(MDL_LAMBDA__EXP__2*MDL_SW
     $ *MDL_SQRT__2)
      GC_922 = (MDL_CPQ3IX32*MDL_EE*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SW*MDL_SQRT__2)+(MDL_CPQ3X32*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(MDL_LAMBDA__EXP__2*MDL_SW
     $ *MDL_SQRT__2)
      GC_923 = -(MDL_CPTBI*MDL_EE*MDL_VEV__EXP__2)/(2.000000D+00
     $ *MDL_LAMBDA__EXP__2*MDL_SW*MDL_SQRT__2)-(MDL_CPTB*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(2.000000D+00*MDL_LAMBDA__EXP__2
     $ *MDL_SW*MDL_SQRT__2)
      GC_924 = (MDL_CPTBI*MDL_EE*MDL_VEV__EXP__2)/(2.000000D+00
     $ *MDL_LAMBDA__EXP__2*MDL_SW*MDL_SQRT__2)-(MDL_CPTB*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(2.000000D+00*MDL_LAMBDA__EXP__2
     $ *MDL_SW*MDL_SQRT__2)
      GC_929 = -(MDL_CPTBIX31*MDL_EE*MDL_VEV__EXP__2)/(2.000000D+00
     $ *MDL_LAMBDA__EXP__2*MDL_SW*MDL_SQRT__2)-(MDL_CPTBX31*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(2.000000D+00*MDL_LAMBDA__EXP__2
     $ *MDL_SW*MDL_SQRT__2)
      GC_930 = (MDL_CPTBIX31*MDL_EE*MDL_VEV__EXP__2)/(2.000000D+00
     $ *MDL_LAMBDA__EXP__2*MDL_SW*MDL_SQRT__2)-(MDL_CPTBX31*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(2.000000D+00*MDL_LAMBDA__EXP__2
     $ *MDL_SW*MDL_SQRT__2)
      GC_931 = -(MDL_CPTBIX32*MDL_EE*MDL_VEV__EXP__2)/(2.000000D+00
     $ *MDL_LAMBDA__EXP__2*MDL_SW*MDL_SQRT__2)-(MDL_CPTBX32*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(2.000000D+00*MDL_LAMBDA__EXP__2
     $ *MDL_SW*MDL_SQRT__2)
      GC_932 = (MDL_CPTBIX32*MDL_EE*MDL_VEV__EXP__2)/(2.000000D+00
     $ *MDL_LAMBDA__EXP__2*MDL_SW*MDL_SQRT__2)-(MDL_CPTBX32*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(2.000000D+00*MDL_LAMBDA__EXP__2
     $ *MDL_SW*MDL_SQRT__2)
      GC_933 = -(MDL_CPB*MDL_CW*MDL_EE*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(2.000000D+00*MDL_LAMBDA__EXP__2*MDL_SW)-(MDL_CPB*MDL_EE
     $ *MDL_COMPLEXI*MDL_SW*MDL_VEV__EXP__2)/(2.000000D+00*MDL_CW
     $ *MDL_LAMBDA__EXP__2)
      GC_934 = -(MDL_CPBIX31*MDL_CW*MDL_EE*MDL_VEV__EXP__2)/(2.000000D
     $ +00*MDL_LAMBDA__EXP__2*MDL_SW)-(MDL_CPBX31*MDL_CW*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(2.000000D+00*MDL_LAMBDA__EXP__2
     $ *MDL_SW)-(MDL_CPBIX31*MDL_EE*MDL_SW*MDL_VEV__EXP__2)/(2.000000D
     $ +00*MDL_CW*MDL_LAMBDA__EXP__2)-(MDL_CPBX31*MDL_EE*MDL_COMPLEXI
     $ *MDL_SW*MDL_VEV__EXP__2)/(2.000000D+00*MDL_CW
     $ *MDL_LAMBDA__EXP__2)
      GC_935 = (MDL_CPBIX31*MDL_CW*MDL_EE*MDL_VEV__EXP__2)/(2.000000D
     $ +00*MDL_LAMBDA__EXP__2*MDL_SW)-(MDL_CPBX31*MDL_CW*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(2.000000D+00*MDL_LAMBDA__EXP__2
     $ *MDL_SW)+(MDL_CPBIX31*MDL_EE*MDL_SW*MDL_VEV__EXP__2)/(2.000000D
     $ +00*MDL_CW*MDL_LAMBDA__EXP__2)-(MDL_CPBX31*MDL_EE*MDL_COMPLEXI
     $ *MDL_SW*MDL_VEV__EXP__2)/(2.000000D+00*MDL_CW
     $ *MDL_LAMBDA__EXP__2)
      GC_936 = -(MDL_CPBIX32*MDL_CW*MDL_EE*MDL_VEV__EXP__2)/(2.000000D
     $ +00*MDL_LAMBDA__EXP__2*MDL_SW)-(MDL_CPBX32*MDL_CW*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(2.000000D+00*MDL_LAMBDA__EXP__2
     $ *MDL_SW)-(MDL_CPBIX32*MDL_EE*MDL_SW*MDL_VEV__EXP__2)/(2.000000D
     $ +00*MDL_CW*MDL_LAMBDA__EXP__2)-(MDL_CPBX32*MDL_EE*MDL_COMPLEXI
     $ *MDL_SW*MDL_VEV__EXP__2)/(2.000000D+00*MDL_CW
     $ *MDL_LAMBDA__EXP__2)
      GC_937 = (MDL_CPBIX32*MDL_CW*MDL_EE*MDL_VEV__EXP__2)/(2.000000D
     $ +00*MDL_LAMBDA__EXP__2*MDL_SW)-(MDL_CPBX32*MDL_CW*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(2.000000D+00*MDL_LAMBDA__EXP__2
     $ *MDL_SW)+(MDL_CPBIX32*MDL_EE*MDL_SW*MDL_VEV__EXP__2)/(2.000000D
     $ +00*MDL_CW*MDL_LAMBDA__EXP__2)-(MDL_CPBX32*MDL_EE*MDL_COMPLEXI
     $ *MDL_SW*MDL_VEV__EXP__2)/(2.000000D+00*MDL_CW
     $ *MDL_LAMBDA__EXP__2)
      GC_938 = -(MDL_CPQM*MDL_CW*MDL_EE*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(2.000000D+00*MDL_LAMBDA__EXP__2*MDL_SW)-(MDL_CPQM*MDL_EE
     $ *MDL_COMPLEXI*MDL_SW*MDL_VEV__EXP__2)/(2.000000D+00*MDL_CW
     $ *MDL_LAMBDA__EXP__2)
      GC_939 = -((MDL_CPQ3*MDL_CW*MDL_EE*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SW))-(MDL_CPQM*MDL_CW*MDL_EE
     $ *MDL_COMPLEXI*MDL_VEV__EXP__2)/(2.000000D+00*MDL_LAMBDA__EXP__2
     $ *MDL_SW)-(MDL_CPQ3*MDL_EE*MDL_COMPLEXI*MDL_SW*MDL_VEV__EXP__2)
     $ /(MDL_CW*MDL_LAMBDA__EXP__2)-(MDL_CPQM*MDL_EE*MDL_COMPLEXI
     $ *MDL_SW*MDL_VEV__EXP__2)/(2.000000D+00*MDL_CW
     $ *MDL_LAMBDA__EXP__2)
      END
