ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP7()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_495 = -(MDL_CUD1IX3332/MDL_LAMBDA__EXP__2)+(MDL_CUD1X3332
     $ *MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_496 = MDL_CUD1IX3332/MDL_LAMBDA__EXP__2+(MDL_CUD1X3332
     $ *MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_505 = -(MDL_CUD8IX3331/MDL_LAMBDA__EXP__2)+(MDL_CUD8X3331
     $ *MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_506 = MDL_CUD8IX3331/MDL_LAMBDA__EXP__2+(MDL_CUD8X3331
     $ *MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_507 = -(MDL_CUD8IX3332/MDL_LAMBDA__EXP__2)+(MDL_CUD8X3332
     $ *MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_508 = MDL_CUD8IX3332/MDL_LAMBDA__EXP__2+(MDL_CUD8X3332
     $ *MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_557 = (MDL_CQB1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_558 = (MDL_CQB8*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_559 = (MDL_CQD1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_560 = (MDL_CQD8*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_571 = (MDL_CQQ8*MDL_COMPLEXI)/(2.000000D+00
     $ *MDL_LAMBDA__EXP__2)
      GC_573 = (MDL_CQT1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_574 = (MDL_CQT8*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_575 = (MDL_CQU1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_576 = (MDL_CQU8*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_577 = (MDL_CTB1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_578 = (MDL_CTB8*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_579 = (MDL_CTD1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_580 = (MDL_CTD8*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_589 = (MDL_CTQ1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_590 = (MDL_CTQ8*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_592 = (MDL_CTU1*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_593 = (MDL_CTU8*MDL_COMPLEXI)/MDL_LAMBDA__EXP__2
      GC_721 = (MDL_CTZ*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_722 = (MDL_CTZI*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      END
