ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP8()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_725 = (MDL_CTG*MDL_COMPLEXI*MDL_GSTRONG*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_726 = (MDL_CTGI*MDL_GSTRONG*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_738 = (MDL_CTP*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_739 = (MDL_CTPI*MDL_VEV__EXP__2)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_741 = -((MDL_CBWI*MDL_VEV)/MDL_LAMBDA__EXP__2)+(MDL_CBW
     $ *MDL_COMPLEXI*MDL_VEV)/MDL_LAMBDA__EXP__2
      GC_742 = (MDL_CBWI*MDL_VEV)/MDL_LAMBDA__EXP__2+(MDL_CBW
     $ *MDL_COMPLEXI*MDL_VEV)/MDL_LAMBDA__EXP__2
      GC_747 = -((MDL_CBWIX31*MDL_VEV)/MDL_LAMBDA__EXP__2)+(MDL_CBWX31
     $ *MDL_COMPLEXI*MDL_VEV)/MDL_LAMBDA__EXP__2
      GC_748 = (MDL_CBWIX31*MDL_VEV)/MDL_LAMBDA__EXP__2+(MDL_CBWX31
     $ *MDL_COMPLEXI*MDL_VEV)/MDL_LAMBDA__EXP__2
      GC_749 = -((MDL_CBWIX32*MDL_VEV)/MDL_LAMBDA__EXP__2)+(MDL_CBWX32
     $ *MDL_COMPLEXI*MDL_VEV)/MDL_LAMBDA__EXP__2
      GC_750 = (MDL_CBWIX32*MDL_VEV)/MDL_LAMBDA__EXP__2+(MDL_CBWX32
     $ *MDL_COMPLEXI*MDL_VEV)/MDL_LAMBDA__EXP__2
      GC_751 = -((MDL_CTAIX13*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ )+(MDL_CTAX13*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_752 = (MDL_CTAIX13*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ +(MDL_CTAX13*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_753 = -((MDL_CTAIX23*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ )+(MDL_CTAX23*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_754 = (MDL_CTAIX23*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ +(MDL_CTAX23*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_755 = -((MDL_CTAIX31*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ )+(MDL_CTAX31*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_756 = (MDL_CTAIX31*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ +(MDL_CTAX31*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_757 = -((MDL_CTAIX32*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ )+(MDL_CTAX32*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_758 = (MDL_CTAIX32*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ +(MDL_CTAX32*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_767 = -((MDL_CTWI*MDL_VEV)/MDL_LAMBDA__EXP__2)+(MDL_CTW
     $ *MDL_COMPLEXI*MDL_VEV)/MDL_LAMBDA__EXP__2
      GC_768 = (MDL_CTWI*MDL_VEV)/MDL_LAMBDA__EXP__2+(MDL_CTW
     $ *MDL_COMPLEXI*MDL_VEV)/MDL_LAMBDA__EXP__2
      GC_769 = -((MDL_CTZIX13*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ )+(MDL_CTZX13*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_770 = (MDL_CTZIX13*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ +(MDL_CTZX13*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_771 = -((MDL_CTZIX23*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ )+(MDL_CTZX23*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_772 = (MDL_CTZIX23*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ +(MDL_CTZX23*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      GC_773 = -((MDL_CTZIX31*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
     $ )+(MDL_CTZX31*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)
      END
