ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      SUBROUTINE COUP1()

      IMPLICIT NONE
      INCLUDE 'model_functions.inc'

      DOUBLE PRECISION PI, ZERO
      PARAMETER  (PI=3.141592653589793D0)
      PARAMETER  (ZERO=0D0)
      INCLUDE 'input.inc'
      INCLUDE 'coupl.inc'
      GC_1 = -(MDL_EE*MDL_COMPLEXI)/3.000000D+00
      GC_2 = (2.000000D+00*MDL_EE*MDL_COMPLEXI)/3.000000D+00
      GC_649 = (MDL_EE*MDL_COMPLEXI)/(MDL_SW*MDL_SQRT__2)
      GC_650 = -(MDL_CW*MDL_EE*MDL_COMPLEXI)/(2.000000D+00*MDL_SW)
      GC_651 = (MDL_CW*MDL_EE*MDL_COMPLEXI)/(2.000000D+00*MDL_SW)
      GC_660 = -(MDL_EE*MDL_COMPLEXI*MDL_SW)/(6.000000D+00*MDL_CW)
      GC_723 = -((MDL_CBW*MDL_CW*MDL_COMPLEXI*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2))
      GC_724 = -((MDL_CBWI*MDL_CW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))
      GC_736 = -((MDL_CBW*MDL_COMPLEXI*MDL_SW*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2))
      GC_737 = -((MDL_CBWI*MDL_SW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))
      GC_740 = (MDL_CPQ3*MDL_EE*MDL_COMPLEXI*MDL_VEV__EXP__2)
     $ /(MDL_LAMBDA__EXP__2*MDL_SW*MDL_SQRT__2)
      GC_777 = -((MDL_CBWIX13*MDL_CW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))-(MDL_CBWX13*MDL_CW*MDL_COMPLEXI*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_778 = (MDL_CBWIX13*MDL_CW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)-(MDL_CBWX13*MDL_CW*MDL_COMPLEXI*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_779 = -((MDL_CBWIX23*MDL_CW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))-(MDL_CBWX23*MDL_CW*MDL_COMPLEXI*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_780 = (MDL_CBWIX23*MDL_CW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)-(MDL_CBWX23*MDL_CW*MDL_COMPLEXI*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_781 = -((MDL_CBWIX31*MDL_CW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))-(MDL_CBWX31*MDL_CW*MDL_COMPLEXI*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_782 = (MDL_CBWIX31*MDL_CW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)-(MDL_CBWX31*MDL_CW*MDL_COMPLEXI*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_783 = -((MDL_CBWIX32*MDL_CW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))-(MDL_CBWX32*MDL_CW*MDL_COMPLEXI*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_784 = (MDL_CBWIX32*MDL_CW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)-(MDL_CBWX32*MDL_CW*MDL_COMPLEXI*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_813 = (MDL_CTW*MDL_COMPLEXI*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SW*MDL_SQRT__2)-(MDL_CTZ*MDL_CW*MDL_COMPLEXI*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SW*MDL_SQRT__2)
      GC_814 = (MDL_CTWI*MDL_VEV)/(MDL_LAMBDA__EXP__2*MDL_SW
     $ *MDL_SQRT__2)-(MDL_CTZI*MDL_CW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SW*MDL_SQRT__2)
      GC_857 = -((MDL_CBWIX13*MDL_SW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))-(MDL_CBWX13*MDL_COMPLEXI*MDL_SW*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_858 = (MDL_CBWIX13*MDL_SW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)-(MDL_CBWX13*MDL_COMPLEXI*MDL_SW*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_859 = -((MDL_CBWIX23*MDL_SW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2))-(MDL_CBWX23*MDL_COMPLEXI*MDL_SW*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      GC_860 = (MDL_CBWIX23*MDL_SW*MDL_VEV)/(MDL_LAMBDA__EXP__2
     $ *MDL_SQRT__2)-(MDL_CBWX23*MDL_COMPLEXI*MDL_SW*MDL_VEV)
     $ /(MDL_LAMBDA__EXP__2*MDL_SQRT__2)
      END
