ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MTA,MDL_MW,MDL_MB,MDL_MH,MDL_MZ,MDL_MT

      COMMON/MASSES/ MDL_MTA,MDL_MW,MDL_MB,MDL_MH,MDL_MZ,MDL_MT


      DOUBLE PRECISION MDL_WW,MDL_WT,MDL_WH,MDL_WZ

      COMMON/WIDTHS/ MDL_WW,MDL_WT,MDL_WH,MDL_WZ


      DOUBLE COMPLEX GC_6, GC_7, GC_727, GC_1, GC_2, GC_649, GC_650,
     $  GC_660, GC_590, GC_725, GC_953, GC_954

      COMMON/COUPLINGS/ GC_6, GC_7, GC_727, GC_1, GC_2, GC_649, GC_650
     $ , GC_660, GC_590, GC_725, GC_953, GC_954

