ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of dim6top_LO_UFO-ctG_ctq8'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_727 = ', GC_727
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_649 = ', GC_649
      WRITE(*,2) 'GC_650 = ', GC_650
      WRITE(*,2) 'GC_660 = ', GC_660
      WRITE(*,2) 'GC_590 = ', GC_590
      WRITE(*,2) 'GC_725 = ', GC_725
      WRITE(*,2) 'GC_953 = ', GC_953
      WRITE(*,2) 'GC_954 = ', GC_954
