ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MB,MDL_MW,MDL_MZ,MDL_MTA,MDL_MT,MDL_MH

      COMMON/MASSES/ MDL_MB,MDL_MW,MDL_MZ,MDL_MTA,MDL_MT,MDL_MH


      DOUBLE PRECISION MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      DOUBLE COMPLEX GC_6, GC_7, GC_727, GC_1, GC_2, GC_650, GC_660,
     $  GC_593, GC_725

      COMMON/COUPLINGS/ GC_6, GC_7, GC_727, GC_1, GC_2, GC_650, GC_660
     $ , GC_593, GC_725

